workflows:
  yarn-node-build:
    name: Build (use Yarn)
    environment:
      node: "18"
    scripts:
      - name: Install dependencies (use Yarn)
        script: |
          echo "Enabling corepack so Yarn is available"
          corepack enable || true
          # Try frozen install, fall back to normal install
          yarn install --frozen-lockfile || yarn install
      - name: Build app
        script: |
          echo "Building Next.js app"
          yarn build
    artifacts:
      - .next/**
      - out/**
      - public/**
