workflows:
  android-standalone:
    name: Android Debug & Release
    max_build_duration: 60
    environment:
      node: latest
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          yarn install --frozen-lockfile
      - name: Build PWA
        script: |
          yarn build
      - name: Copy PWA into Capacitor
        script: |
          npx cap sync android
      - name: Build Debug APK
        script: |
          cd android
          ./gradlew assembleDebug
      - name: Build Release APK (unsigned for now)
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk

  ios-standalone:
    name: iOS Debug & Release
    max_build_duration: 60
    environment:
      node: latest
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          yarn install --frozen-lockfile
      - name: Build PWA
        script: |
          yarn build
      - name: Copy PWA into Capacitor
        script: |
          npx cap sync ios
      - name: Build Debug IPA
        script: |
          xcodebuild \
            -workspace ios/App/App.xcworkspace \
            -scheme App \
            -configuration Debug \
            -sdk iphoneos \
            -derivedDataPath build
      - name: Build Release IPA (unsigned for now)
        script: |
          xcodebuild \
            -workspace ios/App/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath build
    artifacts:
      - build/**/*.ipa
