workflows:
  android-ios-workflow:
    name: Android & iOS Debug + Release
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.abi.biblemaps"
      java: 17
      node: 18
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install -g yarn
          yarn install --frozen-lockfile

      - name: Build PWA for Capacitor
        script: |
          yarn build

      - name: Copy web assets into Capacitor
        script: |
          npx cap sync

      # ---------------- ANDROID ----------------
      - name: Build Debug APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Build Release APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease

      # ---------------- iOS ----------------
      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install

      - name: Build iOS Debug
        script: |
          xcodebuild \
            -workspace ios/App/App.xcworkspace \
            -scheme App \
            -configuration Debug \
            -sdk iphoneos \
            -archivePath $CM_BUILD_DIR/ios/App.xcarchive \
            archive

      - name: Build iOS Release
        script: |
          xcodebuild \
            -workspace ios/App/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $CM_BUILD_DIR/ios/AppRelease.xcarchive \
            archive

    artifacts:
      - android/app/build/outputs/**/*.apk
      - $CM_BUILD_DIR/ios/**/*.xcarchive

    publishing:
      email:
        recipients:
          - your-email@example.com
