workflows:
  android-workflow:
    name: Android Debug + Release
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.abi.biblemaps"
      flutter: stable
      xcode: latest
      java: 17
      node: 20.11.1
    cache:
      cache_paths:
        - $FCI_BUILD_DIR/node_modules
        - $HOME/.gradle/caches
        - $HOME/.pub-cache
    scripts:
      - name: Install dependencies
        script: yarn install
      - name: Build PWA
        script: yarn build
      - name: Copy PWA into Capacitor (Android)
        script: npx cap sync android
      - name: Build Debug APK
        script: |
          cd android
          ./gradlew assembleDebug
      - name: Build Release APK (unsigned)
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk

  ios-workflow:
    name: iOS Debug + Release
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.abi.biblemaps"
      flutter: stable
      xcode: latest
      java: 17
      node: 20.11.1
    cache:
      cache_paths:
        - $FCI_BUILD_DIR/node_modules
        - $HOME/Library/Caches/CocoaPods
        - $HOME/.pub-cache
    scripts:
      - name: Install dependencies
        script: yarn install
      - name: Build PWA
        script: yarn build
      - name: Copy PWA into Capacitor (iOS)
        script: npx cap sync ios
      - name: Build iOS Debug
        script: |
          cd ios
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Debug \
            -sdk iphonesimulator \
            -derivedDataPath build
      - name: Build iOS Release (unsigned)
        script: |
          cd ios
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath build
    artifacts:
      - ios/build/**/*.app
      - ios/build/**/*.ipa

  android-ios-workflow:
    name: Android & iOS Debug + Release
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.abi.biblemaps"
      flutter: stable
      xcode: latest
      java: 17
      node: 20.11.1
    cache:
      cache_paths:
        - $FCI_BUILD_DIR/node_modules
        - $HOME/.gradle/caches
        - $HOME/Library/Caches/CocoaPods
        - $HOME/.pub-cache
    scripts:
      - name: Install dependencies
        script: yarn install
      - name: Build PWA
        script: yarn build
      - name: Copy PWA into Capacitor (Android + iOS)
        script: npx cap sync
      - name: Build Android Debug + Release
        script: |
          cd android
          ./gradlew assembleDebug
          ./gradlew assembleRelease
      - name: Build iOS Debug + Release
        script: |
          cd ios
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Debug \
            -sdk iphonesimulator \
            -derivedDataPath build
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath build
    artifacts:
      - android/app/build/outputs/**/*.apk
      - ios/build/**/*.app
      - ios/build/**/*.ipa
