workflows:
  web-app:
    name: Bible Maps Web App
    environment:
      node: 18
    scripts:
      - name: Force standalone Yarn project
        script: export YARN_IGNORE_PATH=1
      - name: Install dependencies
        script: yarn install --immutable
      - name: Build Next.js app
        script: yarn build
      - name: Export static site
        script: yarn export
    artifacts:
      - out/**



