workflows:
  android-debug:
    name: Android Debug Build
    max_build_duration: 30
    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "com.example.biblemaps"
    scripts:
      - name: Build Debug APK
        script: |
          cd bible-maps-appc-pwa-ready
          npx cap sync android
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk

  android-release:
    name: Android Release Build
    max_build_duration: 30
    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "com.example.biblemaps"
        KEYSTORE_PATH: /tmp/keystore.keystore
        KEYSTORE_PASSWORD: $KEYSTORE_PASSWORD
        KEY_ALIAS: $KEY_ALIAS
        KEY_PASSWORD: $KEY_PASSWORD
    scripts:
      - name: Setup Keystore
        script: |
          if [ -n "$CM_KEYSTORE" ]; then
            echo $CM_KEYSTORE | base64 --decode > $KEYSTORE_PATH
          else
            echo "⚠️ No keystore provided. Build will fail for release."
          fi
      - name: Build Signed Release APK
        script: |
          cd bible-maps-appc-pwa-ready
          npx cap sync android
          cd android
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=$KEYSTORE_PATH \
            -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$KEY_PASSWORD
    artifacts:
      - android/app/build/outputs/**/*.apk

  ios-debug:
    name: iOS Debug Build
    max_build_duration: 60
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Build iOS Debug (Simulator)
        script: |
          cd bible-maps-appc-pwa-ready
          npx cap sync ios
          cd ios
          xcodebuild \
            -workspace App/App.xcworkspace \
            -scheme App \
            -sdk iphonesimulator \
            -configuration Debug \
            build
    artifacts:
      - ios/build/**/*.app

  ios-release:
    name: iOS Release Build
    max_build_duration: 60
    environment:
      xcode: latest
      cocoapods: default
      vars:
        APPLE_TEAM_ID: $APPLE_TEAM_ID
        BUNDLE_ID: "com.example.biblemaps"
        CODE_SIGN_IDENTITY: "Apple Distribution"
        PROVISIONING_PROFILE_UUID: $PROVISIONING_PROFILE_UUID
    scripts:
      - name: Build iOS Release
        script: |
          cd bible-maps-appc-pwa-ready
          npx cap sync ios
          cd ios
          xcodebuild \
            -workspace App/App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            -allowProvisioningUpdates \
            DEVELOPMENT_TEAM=$APPLE_TEAM_ID \
            CODE_SIGN_IDENTITY="$CODE_SIGN_IDENTITY" \
            PROVISIONING_PROFILE_SPECIFIER=$PROVISIONING_PROFILE_UUID
    artifacts:
      - ios/build/**/*.ipa
