workflows:
  nextjs-pwa:
    name: Build Next.js PWA
    environment:
      node: 20
    scripts:
      - name: Install dependencies
        script: |
          npm install -g pnpm
          pnpm install --frozen-lockfile
      - name: Build and export
        script: |
          pnpm build
          pnpm export
    artifacts:
      - out/**
