workflows:
  web-app:
    name: Bible Maps Web App
    environment:
      node: 18
    scripts:
      - name: Install dependencies
        script: yarn install --frozen-lockfile
      - name: Build Next.js app
        script: yarn build
      - name: Export static site
        script: yarn export
    artifacts:
      - out/**


