workflows:
  # ----------------------
  # 1. Codemagic Web Workflow (Next.js PWA)
  # ----------------------
  web-workflow:
    name: Web (Next.js PWA)
    max_build_duration: 20
    environment:
      node: 20.11.1
      vars:
        PACKAGE_MANAGER: yarn
    cache:
      cache_paths:
        - $FCI_BUILD_DIR/node_modules
        - $HOME/.npm
    scripts:
      - name: Setup Yarn
        script: corepack enable
      - name: Validate Yarn
        script: |
          echo "=== validation: yarn & node versions ==="
          yarn --version || (echo "yarn not found" && exit 1)
          node --version || (echo "node not found" && exit 1)
          if [ -f yarn.lock ]; then echo "yarn.lock: present"; else echo "yarn.lock: not present"; fi
      - name: Install dependencies
        script: yarn install --frozen-lockfile
      - name: Build Web
        script: yarn build:web
    artifacts:
      - out/**

  # ----------------------
  # 2. Codemagic Android Workflow
  # ----------------------
  android-workflow:
    name: Android Debug + Release
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.abi.biblemaps"
        PACKAGE_MANAGER: yarn
      node: 20.11.1
      java: 17
    cache:
      cache_paths:
        - $FCI_BUILD_DIR/node_modules
        - $HOME/.npm
        - $HOME/.gradle/caches
    scripts:
      - name: Setup Yarn
        script: corepack enable
      - name: Validate Yarn
        script: |
          echo "=== validation: yarn & node versions ==="
          yarn --version || (echo "yarn not found" && exit 1)
          node --version || (echo "node not found" && exit 1)
          if [ -f yarn.lock ]; then echo "yarn.lock: present"; else echo "yarn.lock: not present"; fi
      - name: Install dependencies
        script: yarn install --frozen-lockfile
      - name: Build Android Debug + Release
        script: yarn ci:android:release
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab

  # ----------------------
  # 3. Codemagic iOS Workflow
  # ----------------------
  ios-workflow:
    name: iOS Debug + Release
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.abi.biblemaps"
        PACKAGE_MANAGER: yarn
      node: 20.11.1
      java: 17
      xcode: latest
    cache:
      cache_paths:
        - $FCI_BUILD_DIR/node_modules
        - $HOME/Library/Caches/CocoaPods
    scripts:
      - name: Setup Yarn
        script: corepack enable
      - name: Validate Yarn
        script: |
          echo "=== validation: yarn & node versions ==="
          yarn --version || (echo "yarn not found" && exit 1)
          node --version || (echo "node not found" && exit 1)
          if [ -f yarn.lock ]; then echo "yarn.lock: present"; else echo "yarn.lock: not present"; fi
      - name: Install dependencies
        script: yarn install --frozen-lockfile
      - name: Build PWA
        script: yarn build:web
      - name: Clean Capacitor assets
        script: |
          rm -rf android/app/src/main/assets/* || true
          rm -rf ios/App/App/public/*
      - name: Copy PWA into Capacitor (iOS)
        script: npx cap sync ios
      - name: Build iOS Debug + Release
        script: |
          cd ios
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Debug \
            -sdk iphonesimulator \
            -derivedDataPath build
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath build
    artifacts:
      - ios/build/**/*.app
      - ios/build/**/*.ipa

  # ----------------------
  # 4. Combined Workflow (optional)
  # ----------------------
  android-ios-workflow:
    name: Android & iOS Debug + Release
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.abi.biblemaps"
        PACKAGE_MANAGER: yarn
      node: 20.11.1
      java: 17
      xcode: latest
    cache:
      cache_paths:
        - $FCI_BUILD_DIR/node_modules
        - $HOME/.npm
        - $HOME/.gradle/caches
        - $HOME/Library/Caches/CocoaPods
    scripts:
      - name: Setup Yarn
        script: corepack enable
      - name: Validate Yarn
        script: |
          echo "=== validation: yarn & node versions ==="
          yarn --version || (echo "yarn not found" && exit 1)
          node --version || (echo "node not found" && exit 1)
          if [ -f yarn.lock ]; then echo "yarn.lock: present"; else echo "yarn.lock: not present"; fi
      - name: Install dependencies
        script: yarn install --frozen-lockfile
      - name: Build Web
        script: yarn build:web
      - name: Clean Capacitor assets
        script: |
          rm -rf android/app/src/main/assets/*
          rm -rf ios/App/App/public/*
      - name: Copy PWA into Capacitor (Android + iOS)
        script: npx cap sync
      - name: Build Android Debug + Release
        script: |
          cd android
          ./gradlew assembleDebug
          ./gradlew assembleRelease
          ./gradlew bundleRelease
      - name: Build iOS Debug + Release
        script: |
          cd ios
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Debug \
            -sdk iphonesimulator \
            -derivedDataPath build
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath build
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
      - ios/build/**/*.app
      - ios/build/**/*.ipa
